use sales;
-- Which products have been sold the most in the last month?--
Select product_id, count(io.product_id), month(o.order_date)
from order_items as io
join orders as o on o.order_id = io.order_id
where month(o.order_date) = month(date_sub(curdate(), interval 1 month))
group by product_id,  month(o.order_date) 
order by count(io.product_id) desc;

-- What is the total revenue generated by the shop in the last 30 days --
select sum(total_price) as total_revenue
from orders
where month(order_date) = month(date_sub(curdate(), interval 30 day));

-- Find the highest-value order made in the shop.--
select order_id, total_price
from orders
group by order_id, total_price
order by total_price desc
limit 1;

--  Which day of the week has the highest number of orders placed?--
select dayname(order_date) as day_of_week, count(order_id) as no_of_orders
from orders
group by day_of_week;

-- What is the average order value for each customer? --
select customer_id, avg(total_price)  as avg_price
from orders
group by customer_id;